### PR TITLE
Pull Request for Finding Closure

### LINKED ISSUE #15: Changes not pulled from our repo
This commit from last night with some final copy updates isn't on the site for some reason: https://github.com/SarahTurbin/TheFlux/commit/c901824230dd58dd9b5caafb11431d7a86ce97fc

We also made a bug fix this morning https://github.com/SarahTurbin/TheFlux/commit/58036b3c6dba4fa420a59e15715ed63aba82f2b8 to our repo which would be great if it could be pulled into the main site.

### PR DESCRIPTION
**Pull request by duner**
@zachwise: I'm not sure it likes the pull request so much because I guess we haven't used git to get the changes in already? It's as if we're merging the finished story into a totally empty one, maybe. 

Tries to fix #15

### CODE REVIEW

**Comment by zachwise** [comment]
This is gonna be messy. Can you just clone and push changes to the main repo?

**Comment by duner** [comment]
@zachwise: What do you mean by that?

**Comment by zachwise** [comment]
Just push changes directly to repo

**Comment by duner** [comment]
Closing this. Went about pushing changes this way 40ef62035ed2f911968193518d7c5dbe2c40045d.

**Pull request closed without merging**
